### ISSUE TITLE
Please update the README

### ISSUE THREAD

**Issue by matotim** [Ganitzsh/docker-nes-devkit#1]
Where are the informations ? How does it work ? What does it do ?

**Comment by Sarvok** [comment]
It really do be like that sometimes

**Comment by matotim** [comment]
Instructions unclear, dick stuck in a fan

**Comment by Sarvok** [comment]
It really do

**Comment by Ganitzsh** [comment]
> Instructions unclear, dick stuck in a fan

💯

**Comment by Ganitzsh** [comment]
🔥
